server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummytrack?createDatabaseIfNotExist=true&autoReconnect=true
    username: lucky
    password: Lucky@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
      client:
        client-id:
        client-secret:
      resource:
        id:
        tokenType:
        serviceId:
        userInfoUri:
        preferTokenInfo: false
logging:
  level:
    org:
      hibernate:
        type: trace

#spring.datasource.url=jdbc:mysql://localhost:3306/dummyfaces?createDatabaseIfNotExist=true&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update
## = JPA / HIBERNATE
## ===============================
## Use spring.jpa.properties.* for Hibernate native properties (the prefix is
## stripped before adding them to the entity manager).
## Show or not log for each sql query
#spring.jpa.show-sql=false
